#!/usr/bin/env bash

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)

[[ ${BPAN_ROOT:-} ]] || {
  (
    echo
    echo "Testing requires BPAN to be installed."
    echo "https://github.com/bpan-org/bpan#installation"
  ) >&2
  exit 1
}

source "$BPAN_ROOT/lib/bpan.bash" --

# Moke sure local copy is used:
export PATH=$ROOT/lib:$PATH

bpan:use test-tap
